# reCAPTCHA Configuration
recaptcha.site.key=6LdWciYrAAAAANAwBbwsbxf3NWGOh3EzxnkVxE9q
recaptcha.secret.key=6LdWciYrAAAAAIBcsJRrIY1HIuGtF7wbPK2FPVhJ

# hCaptcha Configuration
hcaptcha.site.key=88ac62a8-f07e-4ae0-8b32-274838befed2
hcaptcha.secret.key=ES_59a6e32810d94b7b83d7f0c5f2961184